---
title: "In Class 6"
author: "Patrick Burke"
date: "3/2/2022"
output: html_document
---

# 1
```{r}
library(tidyverse)

library(shiny)

library(readxl)
df <- read_excel("data/slu_graduates_17_21.xlsx")
df <- df %>% mutate(across(everything(),
                           .fns = ~replace(., . ==  "STATS" , "STAT")))

df_long <- df %>% pivot_longer(3:8, names_to = "type", values_to = "discipline")
df_major <- df_long %>% 
  filter(type == "major1" | type == "major2" | type == "major3")

df_stat <- df_major %>% filter(discipline == "STAT") 
df_statfull <- semi_join(df_long, df_stat, by = "adm_id") %>%
  filter(type == "major1" |
           type == "major2" | 
           type == "major3")

library(shiny)

ui <- fluidPage(
  sidebarLayout(
    mainPanel(plotOutput("plot_sex")))
)

server <- function(input, output, session) {
  
  output$plot_sex <- renderPlot({
    ggplot(data = df_long, 
           aes(x = sex, y = discipline)) +
      geom_col() +
      coord_flip()
  })
  
}

shinyApp(ui, server)

```

# 2
```{r}
library(shiny); library(tidyverse)
atp_df <- read_csv("data/atp_matches_2019.csv")
wta_df <- read_csv("data/wta_matches_2019.csv")
both_df <- bind_rows(atp_df, wta_df)

both_long <- both_df %>% pivot_longer(c(winner_name, loser_name))

## only keep players who have player over 50 matches
both_n50 <- both_long %>% group_by(value) %>% count() %>%
  filter(n > 50)

## construct various statistics
major_tennis <- semi_join(both_long, both_n50, by = c("value"))
major_tennis <- major_tennis %>% mutate(w_svperc = 100 * w_1stIn / w_svpt,
                        l_svperc = 100 * l_1stIn / l_svpt,
                        w_firstwon = 100 * w_1stWon / w_1stIn,
                        l_firstwon = 100 * l_1stWon / l_1stIn,
                        w_secondwon = 100 * w_2ndWon / (w_svpt - w_1stIn),
                        l_secondwon = 100 * l_2ndWon / (l_svpt - l_1stIn))

major_tennis_w <- major_tennis %>% filter(name == "winner_name")
major_tennis_l <- major_tennis %>% filter(name == "loser_name")

w_small <- major_tennis_w %>% select(value, winner_seed, w_ace, w_df, w_svperc,
                                     w_firstwon, w_secondwon) %>%
  rename(seed = winner_seed, ace = w_ace, df = w_df, svperc = w_svperc,
         firstwon = w_firstwon, secondwon = w_secondwon)

l_small <- major_tennis_l %>% select(value, loser_seed, l_ace, l_df, l_svperc, l_firstwon, l_secondwon)  %>%
  rename(seed = loser_seed, ace = l_ace, df = l_df, svperc = l_svperc,
         firstwon = l_firstwon, secondwon = l_secondwon)

df <- bind_rows(w_small, l_small) %>%
  rename(player = "value")
df

var_choices <- names(df)[3:7]

library(shiny)

ui <- fluidPage(
  sidebarLayout(sidebarPanel(
    selectizeInput("playerchoice",
                   label = "Choose a Player", choices = levels(factor(df$player)),
                   selected = "Aryna Sabalenka"),
    radioButtons("varchoice", label = "Choose a Statistic",
                 choices = var_choices)),
    mainPanel(plotOutput("histgraph"))
  )
  sidebarLayout((sidebarPanel(
        selectizeInput("playerchoice2",
                   label = "Choose a second Player", 
                   choices = levels(factor(df$player)),
                   selected = "Aryna Sabalenka"),
    radioButtons("varchoice2", label = "Choose a Statistic",
                 choices = var_choices)),
    mainPanel(plotOutput("box_plot"))
                 ))
)

server <- function(input, output, session) {
  
  df_sub <- reactive({
    df %>% filter(player == input$playerchoice)
  })
  
  
  hist_plot <- reactive({
    ggplot(df_sub(), aes(x = .data[[input$varchoice]])) +
      geom_histogram(colour = "black", fill = "white", bins = 15)
  })
  
  output$histgraph <- renderPlot({
    hist_plot()
  })
  df_sub2 <- reactive({
    df %>% filter(player == input$playerchoice2)
  })
  
  box_plot <- reactive({
      ggplot(df_sub(), aes(x = .data[[input$varchoice2]], 
                           y = .data[[input$playerchoice2]])) +
        geom_boxplot(colour = "black", fill = "white")
  })
}

shinyApp(ui, server)
```


